### PR TITLE
feat+docs: Added a streaming parser.

### PR DESCRIPTION
**Pull request by Easyoakland**
[Here](https://github.com/rosetta-rs/parse-rosetta-rs) it was indicated "?" for if this crate supports streaming input.
This is an example which shows that, yes, it does support this type of behavior. In fact, I believe that this can work better than the nom approach of allocating chunks and attempting to repeatedly parse while backing out every time there isn't enough data. The iterator can handle the buffering, blocking, and collecting of new elements as necessary so that no explicit backing out is necessary and it can simply block until the minimum number of needed items are available.
I doubt this implementation is the best that could exist but it should work fine as a demonstration.
While writing it seemed like it would be worth considering making `fn location(&self) -> Self::Location` into `fn location(&mut self) -> Self::Location`

### CODE REVIEW

**Comment by jsdw** [comment]
Thanks for writing this example! I'm away the rest of this week most probably but will have more of a look at this and your other PR at some point when I have time :)

**Comment by Easyoakland** [comment]
Added `StreamTokens` with example. Meant for use when parsing a stream of input such as a `TcpStream` or other `Reader::bytes`. The example is uses `Stdin` as the stream source.

**Comment by jsdw** [comment]
I'm wondering; how would you feel about sticking this in a crate like `yap-streaming` or something? Since it doesn't require any additional code in `yap` to work, it could be developed independently and `yap` could point to it as an approach to handle streaming use cases :)

(Maybe at some point I'll have time to think more about it and support it myself, but I've clearly been quite slow at that!)

**Comment by Easyoakland** [comment]
I'm not totally opposed.

If your reasoning is just you don't want to feel pressured to look this over, I can just use my fork until this is merged (`git = "..."`), so it's not a big deal.

If you reasoning is you don't want to look at this long term or you don't want to support this, then sure, I'll create a new crate. I suppose I could include an explanation why this is significantly preferable to `nom::*::streaming` in the README.

Let me know which it is.

**Comment by jsdw** [comment]
My reasoning is partly that I don't have much bandwidth lately and don't want to be a blocker for this sort of thing, and partly that there's an appeal to me anyway of keeping this crate fairly "basic", and allowing "extensions" like this to be developed independently in separate crates.

So if you're up for it, a new crate with this streaming support would be awesome I think :)

**Comment by Easyoakland** [comment]
New crate is here: https://crates.io/crates/yap_streaming

**Pull request closed without merging**
